#!/bin/bash
# docker-temci
# Copyright (C) 2016  jitakirin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# a proxy for tests
# will just run python as usual, unless parameters to start a web
# server are passed in which case it'll ignore them
if [[ $* == *"-m http.server"* ]]; then
  echo Serving HTTP on 0.0.0.0 port 8000 ...
  exit
fi

exec python "$@"
